#!/usr/bin/env bash

#  running out of inotify user watches
# https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached

sudo -v
sudo sysctl fs.inotify.max_user_watches=$(($(cat /proc/sys/fs/inotify/max_user_watches)*2))
